version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  db:
    image: mariadb:latest
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD:
      PMA_HOST: db
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - elasticsearch
    env_file:
      - .env